name: docker_mlflow_example
services:
  sftp:
    image: atmoz/sftp
    container_name: sftp
    ports:
      - ${SFTP_PORT-2222}:22
    command: ${SFTP_USER-mlflow}:${SFTP_PASSWORD}:${SFTP_UID-1000}::data
    volumes:
      - ./sftp/data:/home/${SFTP_USER}/data
  database:
    build:
      context: ./postgres/
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      MLFLOW_DB_USER: ${MLFLOW_DB_USER-mlflow}
      MLFLOW_DB_PASSWORD: ${MLFLOW_DB_PASSWORD}
    user: ${POSTGRES_UID-1000}:${POSTGRES_GID-1000}
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
    restart: unless-stopped
  mlflow:
    build:
      dockerfile: ./Dockerfile
      context: ./mlflow
      args:
        MLFLOW_USERNAME: ${MLFLOW_USERNAME-mlflow}
        MLFLOW_UID: ${MLFLOW_UID-1000}
        MLFLOW_GID: ${MLFLOW_GID-1000}
        MLFLOW_PORT: ${MLFLOW_PORT-5000}
    container_name: mlflow
    user: ${MLFLOW_UID-1000}:${MLFLOW_GID-1000}
    command: >
      mlflow server
    ports:
      - ${MLFLOW_PORT-5000}:5000
    expose:
      - 5000
    restart: unless-stopped
  #   volumes:
  #     - ./data:/home/${JUPYTER_USERNAME-jovyan}/data:rw
  #     - ./notebooks:/home/${JUPYTER_USERNAME-jovyan}/notebooks:rw