#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $MLFLOW_DB_USER WITH PASSWORD '$MLFLOW_DB_PASSWORD';
    CREATE DATABASE mlflow;
    ALTER DATABASE mlflow OWNER TO $MLFLOW_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE mlflow TO $MLFLOW_DB_USER;
    GRANT ALL ON SCHEMA public TO $MLFLOW_DB_USER;
EOSQL